# 服务名称
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/fruit?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: root
    password: s123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
# 启动端口号
server:
  port: 8093
# Eureka 服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # 配置优先使用IP地址注册服务
  instance:
    prefer-ip-address: true
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic





